"""Visual type candidate filter module for Phase 4 Step 8.

Supports filtering by visual presence:
1. Structural visual types:
   - 'qr' / 'qr_code': verified via OpenCV QR detector regions, visual_metadata, and QR document categories
   - 'signature' / 'sig': verified via signature metadata, category, and document naming
   - 'stamp' / 'seal': verified via stamp/seal metadata, category, and document naming
2. Open-vocabulary visual types (e.g. 'laptop', 'car', 'smartphone', 'mug'):
   - Verified via existing modular CLIP VisualRefiner region similarity (threshold >= 0.245)
   - Zero additional models loaded; reuses existing singleton VisualRefiner instance
"""

from typing import List, Dict, Any, Set, Optional

from app import database


def _get_qr_image_ids() -> Set[int]:
    """Identifies all document IDs with a detected QR code."""
    qr_ids: Set[int] = set()
    # 1. Visual regions generated by QR detector
    try:
        all_regs = database.get_all_visual_regions()
        for r in all_regs:
            if r.get("region_source") == "qr_detector":
                qr_ids.add(r["image_id"])
    except Exception:
        pass
    return qr_ids


def filter_by_visual_type(
    rows: List[Dict[str, Any]],
    visual_type: Optional[str],
    visual_refiner=None,
) -> Set[int]:
    """
    Filters rows by visual object type presence.
    Supports structural types ('qr', 'signature', 'stamp') and open-vocabulary concepts ('laptop', 'car', etc.).
    """
    if not visual_type or not visual_type.strip():
        return {r["id"] for r in rows if "id" in r}

    norm = visual_type.strip().lower()
    matching_ids: Set[int] = set()

    # 1. QR code filter
    if norm in ("qr", "qr_code", "qr-code", "qrcode"):
        qr_detector_ids = _get_qr_image_ids()
        for r in rows:
            row_id = r.get("id")
            if row_id is None:
                continue
            if row_id in qr_detector_ids:
                matching_ids.add(row_id)
                continue
            cat = (r.get("category") or "").strip().lower()
            name = (r.get("image_name") or "").strip().lower()
            if cat in ("positive", "multi_qr", "qr") or "qr" in name:
                matching_ids.add(row_id)
                continue
            v_meta = r.get("visual_metadata") or {}
            if isinstance(v_meta, dict):
                objs = v_meta.get("objects", [])
                if any(o.get("type", "").lower() in ("qr", "qr_code") or "qr" in o.get("label", "").lower() for o in objs):
                    matching_ids.add(row_id)
        return matching_ids

    # 2. Signature filter
    if norm in ("signature", "signatures", "sig", "sign"):
        for r in rows:
            row_id = r.get("id")
            if row_id is None:
                continue
            cat = (r.get("category") or "").strip().lower()
            name = (r.get("image_name") or "").strip().lower()
            if "sign" in cat or "sign" in name:
                matching_ids.add(row_id)
                continue
            v_meta = r.get("visual_metadata") or {}
            if isinstance(v_meta, dict):
                objs = v_meta.get("objects", [])
                if any("sign" in o.get("type", "").lower() or "sign" in o.get("label", "").lower() for o in objs):
                    matching_ids.add(row_id)
        return matching_ids

    # 3. Stamp / Seal filter
    if norm in ("stamp", "stamps", "seal", "seals"):
        for r in rows:
            row_id = r.get("id")
            if row_id is None:
                continue
            cat = (r.get("category") or "").strip().lower()
            name = (r.get("image_name") or "").strip().lower()
            if "stamp" in cat or "seal" in cat or "stamp" in name or "seal" in name:
                matching_ids.add(row_id)
                continue
            v_meta = r.get("visual_metadata") or {}
            if isinstance(v_meta, dict):
                objs = v_meta.get("objects", [])
                if any(
                    "stamp" in o.get("type", "").lower() or "seal" in o.get("type", "").lower() or
                    "stamp" in o.get("label", "").lower() or "seal" in o.get("label", "").lower()
                    for o in objs
                ):
                    matching_ids.add(row_id)
        return matching_ids

    # 4. Open-vocabulary visual concept (e.g. 'laptop', 'car', 'smartphone', etc.)
    # First: check category / metadata tokens
    for r in rows:
        row_id = r.get("id")
        if row_id is None:
            continue
        cat = (r.get("category") or "").strip().lower()
        name = (r.get("image_name") or "").strip().lower()
        if norm in cat or norm in name:
            matching_ids.add(row_id)

    # Second: reuse modular CLIP VisualRefiner to score candidate patches against visual_type
    try:
        if visual_refiner is None:
            from app.visual_refinement.clip_refiner import get_visual_refiner
            visual_refiner = get_visual_refiner()

        all_regs = database.get_all_visual_regions()
        if all_regs:
            q_vec = visual_refiner.encode_query(norm)
            scored = visual_refiner.score_candidate_regions(q_vec, all_regs, threshold=0.245)
            matching_ids.update(scored.keys())
    except Exception as e:
        print(f"[Visual Filter] Open-vocabulary scoring warning: {e}")

    return matching_ids
